### ISSUE TITLE
llama inference start is failing looking for .pth checkpoint file 

### ISSUE THREAD

**Issue by vishnudev-k** [meta-llama/llama-agentic-system#14]
I have downloaded the model using 
`llama download --hf-token hf_xxxxx  meta-llama/Meta-Llama-3.1-8B-Instruct`

```
inference_config:
  impl_config:
    impl_type: "inline"
    checkpoint_config:
      checkpoint:
        checkpoint_type: "pytorch"
        checkpoint_dir: ~/.llama/checkpoints/Meta-Llama-3.1-8B-Instruct/
        tokenizer_path: ~/.llama/checkpoints/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model
        model_parallel_size: 1
        quantization_format: bf16
    quantization: null
    torch_seed: null
    max_seq_len: 16384
    max_batch_size: 1
```

The server start is failing by looking for the checkpoint file
`llama inference start`

  ```
error_file: /tmp/torchelastic_hk5hsswh/204380df-bca3-4cc3-b370-a151f14f6868_0c5a2uu5/attempt_0/0/error.json
  traceback : Traceback (most recent call last):
    File "xx/xx/.venv/lib64/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
      return f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
    File "xx/xx/.venv/lib64/python3.11/site-packages/llama_toolchain/inference/parallel_utils.py", line 131, in worker_process_entrypoint
      model = init_model_cb()
              ^^^^^^^^^^^^^^^
    File "xx/xx/.venv/lib64/python3.11/site-packages/llama_toolchain/inference/model_parallel.py", line 46, in init_model_cb
      llama = Llama.build(config)
              ^^^^^^^^^^^^^^^^^^^
    File "xx/xx/.venv/lib64/python3.11/site-packages/llama_toolchain/inference/generation.py", line 86, in build
      assert len(checkpoints) > 0, f"no checkpoint files found in {ckpt_dir}"
             ^^^^^^^^^^^^^^^^^^^^
  AssertionError: no checkpoint files found in ~/.llama/checkpoints/Meta-Llama-3.1-8B-Instruct/
```

**Comment by prashanthcheemala** [comment]
Change this  checkpoint_dir: ~/.llama/checkpoints/Meta-Llama-3.1-8B-Instruct/ to   ~/.llama/checkpoints/Meta-Llama-3.1-8B-Instruct/original
may this issue will resolve

**Comment by hardikjshah** [comment]
`~/.llama/checkpoints/Meta-Llama-3.1-8B-Instruct/original`

HF download downloads the `.pth` files in the `original` folder, so adding that similar to what you did for the tokenizer should solve the problem.

**Comment by vishnudev-k** [comment]
`~/.llama/checkpoints/Meta-Llama-3.1-8B-Instruct/original`
Worked for me.!

**Comment by dltn** [comment]
This should be fixed in 0.0.4; please re-open if you're still having issues!
