### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by Chrecci** [meta-llama/llama-agentic-system#35]
Full issue stack here:

```
/usr/local/lib/python3.10/dist-packages/llama_toolchain/utils.py:43: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  initialize(config_path=relative_path)
Loading config from : /root/.llama/configs/agentic_system/inline.yaml
Yaml config:
------------------------
agentic_system_config:
  impl_config:
    impl_type: inline
    inference_config:
      impl_config:
        impl_type: remote
        url: http://localhost:5000/
  safety_config:
    llama_guard_shield:
      model_dir: /root/.llama/checkpoints/llama3_1_8b_instruct
      excluded_categories: []
      disable_input_check: false
      disable_output_check: false
    prompt_guard_shield:
      model_dir: /root/.llama/checkpoints/llama3_1_8b_instruct
sampling_params:
  temperature: 0.0
  strategy: top_p
  top_p: 0.95
  top_k: 0
------------------------
Initializing client for http://localhost:5000/
Loading checkpoint shards:  50% 2/4 [00:46<00:46, 23.26s/it]
Traceback (most recent call last):
  File "/content/llama-agentic-system/examples/scripts/vacation.py", line 36, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/llama-agentic-system/examples/scripts/vacation.py", line 18, in main
    asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/content/llama-agentic-system/examples/scripts/multi_turn.py", line 39, in run_main
    client = await get_agent_system_instance(
  File "/usr/local/lib/python3.10/dist-packages/llama_agentic_system/utils.py", line 172, in get_agent_system_instance
    create_response = await api.create_agentic_system(create_request)
  File "/usr/local/lib/python3.10/dist-packages/llama_agentic_system/agentic_system.py", line 704, in create_agentic_system
    input_shields = [
  File "/usr/local/lib/python3.10/dist-packages/llama_agentic_system/agentic_system.py", line 705, in <listcomp>
    shield_config_to_shield(c, self.safety_config)
  File "/usr/local/lib/python3.10/dist-packages/llama_agentic_system/agentic_system.py", line 141, in shield_config_to_shield
    return LlamaGuardShield.instance(
  File "/usr/local/lib/python3.10/dist-packages/llama_toolchain/safety/shields/llama_guard.py", line 114, in instance
    _INSTANCE = LlamaGuardShield(
  File "/usr/local/lib/python3.10/dist-packages/llama_toolchain/safety/shields/llama_guard.py", line 152, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3916, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 4370, in _load_pretrained_model
    state_dict = load_state_dict(shard_file, is_quantized=is_quantized)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 549, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
```

**Comment by YinSonglin1997** [comment]
hey, your llama_guard_shield and prompt_guard_shield's model_dir are wrong, they should not use llama3.1 here, they are meta-llama/Llama-Guard-3-8B and meta-llama/Prompt-Guard-86M.

**Comment by dltn** [comment]
As @YinSonglin1997 said, Llama Guard and Prompt Guard are each separate models and should be downloaded/configured separately from the main Llama 3.1 model.
