### ISSUE TITLE
Issue while installing with python venv instead of conda

### ISSUE THREAD

**Issue by architSrivastav** [meta-llama/llama-agentic-system#42]
While running this comamnd (part of the steps included in readme file): 
llama distribution install --spec local-ollama --name ollama

I get the following error:
Using ollama as the Conda environment for this distribution
Error: conda command not found. Is Conda installed and in your PATH?
Failed to install distribution local-ollama
Traceback (most recent call last):
  File "/home/ec2-user/genai/myenv/bin/llama", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/genai/myenv/lib/python3.10/site-packages/llama_toolchain/cli/llama.py", line 54, in main
    parser.run(args)
  File "/home/ec2-user/genai/myenv/lib/python3.10/site-packages/llama_toolchain/cli/llama.py", line 48, in run
    args.func(args)
  File "/home/ec2-user/genai/myenv/lib/python3.10/site-packages/llama_toolchain/cli/distribution/install.py", line 105, in _run_distribution_install_cmd
    assert return_code == 0, cprint(
AssertionError: None

So it seems even though the readme file says it's ok to follow the steps in either conda or pytohn venv, but actually it expects it to be conda

**Comment by hardikjshah** [comment]
Yeah you are right, currently installing and running `distributions` requires conda.
The readme suggestion is that you can use venv to run the apps ( as the distributions are running as a separate process ).
I ll update the README to reflect that.
